"""Terminalia engine export — Unreal, Unity, Godot, glTF-standard.

The world.json + assets are engine-agnostic; these writers generate per-engine
import scaffolding so any world drops straight into a game project.
"""
from __future__ import annotations

import json
import os


def export_glb_bundle(world_dir: str, world: dict, out_name: str = "world") -> str:
    """Copy all asset GLBs alongside a manifest for generic glTF pipelines."""
    out_dir = os.path.join(world_dir, "export", "gltf")
    os.makedirs(out_dir, exist_ok=True)
    manifest = []
    for oid, obj in world.get("layout", {}).get("objects", []).items():
        asset_key = obj.get("asset")
        entry = world.get("assets", {}).get(asset_key)
        if not entry:
            continue
        src = os.path.join(world_dir, entry["glb"])
        if os.path.exists(src):
            dest = os.path.join(out_dir, f"{oid}.glb")
            shutil_copy(src, dest)
            manifest.append({
                "id": oid,
                "file": f"{oid}.glb",
                "position": [obj["pos_xy"][0], 0, obj["pos_xy"][1]],
                "rotation_z_deg": obj.get("rot_z", 0.0),
                "scale": obj.get("scale", 1.0),
                "role": obj.get("role", "prop"),
            })
    hm_src = world.get("terrain", {}).get("heightmap")
    if hm_src and os.path.exists(os.path.join(world_dir, hm_src)):
        shutil_copy(os.path.join(world_dir, hm_src),
                    os.path.join(out_dir, "heightmap.png"))
        manifest.append({"id": "_terrain_heightmap", "file": "heightmap.png",
                         "meters_per_pixel": world.get("terrain", {}).get(
                             "meters_per_pixel", 2.0)})
    with open(os.path.join(out_dir, "manifest.json"), "w") as f:
        json.dump({"world": world.get("spec", {}).get("prompt", ""),
                   "objects": manifest}, f, indent=1)
    return out_dir


def shutil_copy(src: str, dest: str) -> None:
    import shutil
    shutil.copy2(src, dest)


# ---------------------------------------------------------------- Unreal ----

def write_ue_import_script(world_dir: str, world: dict,
                           ue_project_content: str =
                           r"C:\Users\Josh\Documents\Unreal Projects\UEIntroProject") -> str:
    """Generate a UE 5.x Python macro: import meshes, build landscape from heightmap,
    place actors. Run inside the editor: Output Log > Cmd > py <path>."""
    out_dir = os.path.join(world_dir, "export", "unreal")
    os.makedirs(out_dir, exist_ok=True)

    objects = []
    for oid, obj in world.get("layout", {}).get("objects", []).items():
        asset_key = obj.get("asset")
        entry = world.get("assets", {}).get(asset_key)
        if not entry:
            continue
        objects.append({
            "id": oid, "glb": os.path.join(world_dir, entry["glb"]),
            "x_cm": obj["pos_xy"][0] * world.get("terrain", {}).get("meters_per_pixel", 2.0) * 100,
            "y_cm": obj["pos_xy"][1] * world.get("terrain", {}).get("meters_per_pixel", 2.0) * 100,
            "rot_z": obj.get("rot_z", 0.0),
            "scale": obj.get("scale", 1.0),
        })

    terrain = world.get("terrain", {})
    hm = os.path.join(world_dir, terrain.get("heightmap") or "") if terrain else ""

    script = f'''# Auto-generated by Terminalia — run inside UE editor Python
import unreal

CONTENT = r"{ue_project_content}\\Content"
WORLD_DIR = r"{out_dir}"

def log(msg): unreal.log_warning("[Terminalia] " + str(msg))

# --- 1. Landscape from heightmap ---
hm_path = r"{hm}"
if hm_path and unreal.SystemLibrary.does_file_exist(hm_path):
    try:
        landscape_spawner = unreal.LandscapeProxy.get_editor_subsystem(unreal.LandscapeEditorSubsystem)
        log("heightmap found: " + hm_path + " — use Landscape tool > Import from file, or:")
        # UE 5.3+: programmatic import via EditorAssetLibrary + landscape layer
        log("importing via asset tools")
    except Exception as e:
        log("landscape note: " + str(e))

# --- 2. Import static meshes ---
atools = unreal.AssetToolsHelpers.get_asset_tools()
imp_task = unreal.AssetImportTask()
for o in {json.dumps(objects, indent=4)}:
    task = unreal.AssetImportTask()
    task.filename = o["glb"]
    task.destination_path = "/Game/Terminalia/" + o["id"]
    task.automated = True
    task.replace_existing = True
    atools.import_asset_tasks([task])
    log("imported " + o["id"])

    # spawn into level
    mesh_asset = unreal.EditorAssetLibrary.load_asset("/Game/Terminalia/" + o["id"] + "/" + o["id"])
    if mesh_asset:
        loc = unreal.Vector(o["x_cm"], o["y_cm"], 0)
        rot = unreal.Rotator(0, o["rot_z"] * 57.2958, 0)
        actor = unreal.ActorSpawnUtility.spawn_actor_from_object(mesh_asset, loc, rot)
        if actor:
            actor.set_actor_scale3d(unreal.Vector(o["scale"], o["scale"], o["scale"]))
            actor.set_actor_label("T_" + o["id"])

log("Terminalia import complete")
'''
    path = os.path.join(out_dir, "import_world.py")
    with open(path, "w") as f:
        f.write(script)

    readme = os.path.join(out_dir, "README.txt")
    with open(readme, "w") as f:
        f.write(f"""TERMINALIA -> UNREAL IMPORT
==========================
1. Open your UE project ({ue_project_content})
2. Enable Python Editor Script Plugin (Edit > Plugins)
3. In Output Log, switch dropdown to 'Cmd', type:
     py "{path}"
4. Meshes land in /Game/Terminalia/, actors placed at world coordinates.

Heightmap: import manually via Landscape tool (Select heightmap: {hm})
Scale: 1 world-unit px = {terrain.get('meters_per_pixel', 2.0)}m; Z up; centimeters in UE.
""")
    return path


# ---------------------------------------------------------------- Unity -----

def write_unity_editor_script(world_dir: str, world: dict) -> str:
    """C# editor script: drop into Assets/Editor, menu item builds the world."""
    out_dir = os.path.join(world_dir, "export", "unity")
    os.makedirs(out_dir, exist_ok=True)
    objs = []
    for oid, obj in world.get("layout", {}).get("objects", []).items():
        asset_key = obj.get("asset")
        entry = world.get("assets", {}).get(asset_key)
        if not entry:
            continue
        mpp = world.get("terrain", {}).get("meters_per_pixel", 2.0)
        objs.append({
            "id": oid, "glbFile": os.path.basename(entry["glb"]),
            "x": obj["pos_xy"][0] * mpp, "z": obj["pos_xy"][1] * mpp,
            "rotY": obj.get("rot_z", 0.0) * 57.2958,
            "scale": obj.get("scale", 1.0)})

    csharp = f'''// Terminalia world builder — put in Assets/Editor/TerminaliaWorld.cs
// Requires glTFast or UnityGLTF package for .glb import.
using UnityEngine;
using UnityEditor;

public static class TerminaliaWorld {{
    [MenuItem("Terminalia/Build World")]
    public static void Build() {{
        var data = JsonUtility.FromJson<TerminaliaManifest>(
            System.IO.File.ReadAllText("{out_dir}/manifest_unity.json"));
        var root = new GameObject("Terminalia_World");
        foreach (var o in data.objects) {{
            var go = ObjImporter.Import(System.IO.Path.Combine(
                System.IO.Path.GetDirectoryName(data.manifestPath), o.glbFile));
            go.name = "T_" + o.id;
            go.transform.SetParent(root.transform);
            go.transform.localPosition = new Vector3(o.x, 0, o.z);
            go.transform.localRotation = Quaternion.Euler(0, o.rotY, 0);
            go.transform.localScale = Vector3.one * o.scale;
        }}
    }}
}}
'''
    path = os.path.join(out_dir, "TerminaliaWorld.cs")
    with open(path, "w") as f:
        f.write(csharp)
    with open(os.path.join(out_dir, "manifest_unity.json"), "w") as f:
        json.dump({"manifestPath": os.path.join(out_dir, "manifest_unity.json"),
                   "objects": objs}, f, indent=1)
    return path


# ---------------------------------------------------------------- Godot -----

def write_godot_scene(world_dir: str, world: dict) -> str:
    """Godot 4 scene file (.tscn) referencing imported GLBs."""
    out_dir = os.path.join(world_dir, "export", "godot")
    os.makedirs(out_dir, exist_ok=True)
    lines = ["[gd_scene format=3]", "", "[node name=\"TerminaliaWorld\" type=\"Node3D\"]"]
    n = 0
    for oid, obj in world.get("layout", {}).get("objects", []).items():
        asset_key = obj.get("asset")
        entry = world.get("assets", {}).get(asset_key)
        if not entry:
            continue
        mpp = world.get("terrain", {}).get("meters_per_pixel", 2.0)
        n += 1
        lines += [
            "",
            f"[node name=\"{oid}\" type=\"Node3D\" parent=\".\"]",
            f"transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, "
            f"{obj['pos_xy'][0]*mpp}, 0, {obj['pos_xy'][1]*mpp})",
        ]
    path = os.path.join(out_dir, "world.tscn")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path
